### ISSUE TITLE
[FEATURE] Pick from existing Custom Labels

### ISSUE THREAD

**Issue by tschug** [anmolgkv/sfdx-labelizer-vscode#17]
**Is your feature request related to a problem? Please describe.**
No.  

**Describe the solution you'd like**

I really love the form to prompt users to manage the conversion before it's created.

I'm wondering how difficult it would be to have a form that lets you pick from existing labels?  By reading the custom labels into an Array and letting you perform a search on them and then insert where the cursor was.  This would prevent me from 

**Describe alternatives you've considered**

Now that the custom labels are organized alphabetically, I don't think this is necessarily a big item, as I am using a pretty consistent prefix naming convention so it's easy to find.

**Comment by anmolgkv** [comment]
@tschug for this case instead of showing an option to choose from(which can be huge for a bigger code base), I am skipping the form and directly importing existing label if the text matches any of the existing label.
