### ISSUE TITLE
[feature-request] General

### ISSUE THREAD

**Issue by tprouvot** [anmolgkv/sfdx-labelizer-vscode#2]
Hi @anmolgkv,
Thanks for this plugin this is a great idea 👏 

As a user here is small suggestions which can improve the usage:

- Open a modal to let users fill in `fullName`, `categories`, `language` (with en_US by default), `shortDescription`
Usually you have naming convention to respect and this would also allow users to set the other required information for the label
- Insert the label in the CustomLabel file following alphabetical order instead of the end of the file
- When inserting the import in the lwc .js file, parse the headers in order to insert the import after the last label import (if there is already some imports)

Thank you !

**Comment by anmolgkv** [comment]
Thank you @tprouvot for using it and providing feedback.

I like the idea, will try to include them in next version
